# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73fd1f573a5a1e13ae9fba92e64960ea0c508ae3437b3f74169adc9ffc6854c7bb6f5b5211fe2df488197b4d9020b588b13bf549b12e7a101e19565060dd0bfd

test:
  secret_key_base: 247384cf362767bbc147aed94ebdb58712c1265a4abd4059d4ac6a2945b620157df261c47812a7b900652a2d42f315a08e6995137b7675c101b1c4f1802cf5b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
